# should be overrided in com.user.toml
node_id = 0

auto_assign_id = true


#ID 10->3=29 main robot
[[boards]]
name="Pcom"
id=10
uid="[2B 00 20 00 18 51 35 33 34 39 30 32 00 00 00 00]"

[[boards]]
name="Pbrain"
id=11
uid="[2C 00 24 00 18 51 35 33 34 39 30 32 00 00 00 00]"
path="../../boards/pbrain/Output/pbrain.bin"
simu="../../boards/pbrain/Output/pbrain.sim"

[[boards]]
name="Canon P/G"
id=12
uid="[42 00 28 00 17 50 46 50 58 39 34 20 00 00 00 00]"
path="../../boards/canon/Output/canon.hex"

[[boards]]
name="Canon P/D"
id=13
uid="[42 00 28 00 17 50 46 50 58 39 34 20 00 00 00 00]"
path="../../boards/canon/Output/canon.hex"

[[boards]]
name="Lidar XV11"
id=14
uid=""




#ID 30->49 secondary robot


#ID 50->59 beacons, funny action


#ID 70->79 CocoUI
[[boards]]
name="Damien"
id=70
uid=""

[[boards]]
name="Vincent"
id=72
uid=""

[[boards]]
name="Romain"
id=73
uid=""


#ID 110->120 usb com boards
[[boards]]
name="Houston"
id=110
uid="[2A 00 2F 00 18 51 35 33 34 39 30 32 00 00 00 00]"

